/*
 * This file is generated by jOOQ.
 */
package pl.piotrmacha.lurker.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.piotrmacha.lurker.jooq.Keys;
import pl.piotrmacha.lurker.jooq.Public;
import pl.piotrmacha.lurker.jooq.tables.records.DownloadQueueRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DownloadQueue extends TableImpl<DownloadQueueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.download_queue</code>
     */
    public static final DownloadQueue DOWNLOAD_QUEUE = new DownloadQueue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DownloadQueueRecord> getRecordType() {
        return DownloadQueueRecord.class;
    }

    /**
     * The column <code>public.download_queue.id</code>.
     */
    public final TableField<DownloadQueueRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.download_queue.type</code>.
     */
    public final TableField<DownloadQueueRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.download_queue.url</code>.
     */
    public final TableField<DownloadQueueRecord, String> URL = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.download_queue.entity_id</code>.
     */
    public final TableField<DownloadQueueRecord, Long> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.download_queue.locked_at</code>.
     */
    public final TableField<DownloadQueueRecord, OffsetDateTime> LOCKED_AT = createField(DSL.name("locked_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.download_queue.created_at</code>.
     */
    public final TableField<DownloadQueueRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private DownloadQueue(Name alias, Table<DownloadQueueRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DownloadQueue(Name alias, Table<DownloadQueueRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.download_queue</code> table reference
     */
    public DownloadQueue(String alias) {
        this(DSL.name(alias), DOWNLOAD_QUEUE);
    }

    /**
     * Create an aliased <code>public.download_queue</code> table reference
     */
    public DownloadQueue(Name alias) {
        this(alias, DOWNLOAD_QUEUE);
    }

    /**
     * Create a <code>public.download_queue</code> table reference
     */
    public DownloadQueue() {
        this(DSL.name("download_queue"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DownloadQueueRecord, Long> getIdentity() {
        return (Identity<DownloadQueueRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DownloadQueueRecord> getPrimaryKey() {
        return Keys.DOWNLOAD_QUEUE_PKEY;
    }

    @Override
    public List<Check<DownloadQueueRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("download_queue_type_check"), "((type = ANY (ARRAY['ASSET'::text, 'BOARD'::text, 'TOPIC'::text])))", true)
        );
    }

    @Override
    public DownloadQueue as(String alias) {
        return new DownloadQueue(DSL.name(alias), this);
    }

    @Override
    public DownloadQueue as(Name alias) {
        return new DownloadQueue(alias, this);
    }

    @Override
    public DownloadQueue as(Table<?> alias) {
        return new DownloadQueue(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadQueue rename(String name) {
        return new DownloadQueue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadQueue rename(Name name) {
        return new DownloadQueue(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadQueue rename(Table<?> name) {
        return new DownloadQueue(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueue where(Condition condition) {
        return new DownloadQueue(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueue where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueue where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueue where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadQueue where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadQueue where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadQueue where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadQueue where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueue whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueue whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
