/*
 * This file is generated by jOOQ.
 */
package pl.piotrmacha.lurker.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.piotrmacha.lurker.jooq.Keys;
import pl.piotrmacha.lurker.jooq.Public;
import pl.piotrmacha.lurker.jooq.tables.records.DownloadQueueScheduledRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DownloadQueueScheduled extends TableImpl<DownloadQueueScheduledRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.download_queue_scheduled</code>
     */
    public static final DownloadQueueScheduled DOWNLOAD_QUEUE_SCHEDULED = new DownloadQueueScheduled();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DownloadQueueScheduledRecord> getRecordType() {
        return DownloadQueueScheduledRecord.class;
    }

    /**
     * The column <code>public.download_queue_scheduled.id</code>.
     */
    public final TableField<DownloadQueueScheduledRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.download_queue_scheduled.type</code>.
     */
    public final TableField<DownloadQueueScheduledRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.download_queue_scheduled.url</code>.
     */
    public final TableField<DownloadQueueScheduledRecord, String> URL = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.download_queue_scheduled.entity_id</code>.
     */
    public final TableField<DownloadQueueScheduledRecord, Long> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.download_queue_scheduled.created_at</code>.
     */
    public final TableField<DownloadQueueScheduledRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.download_queue_scheduled.scheduled_at</code>.
     */
    public final TableField<DownloadQueueScheduledRecord, OffsetDateTime> SCHEDULED_AT = createField(DSL.name("scheduled_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private DownloadQueueScheduled(Name alias, Table<DownloadQueueScheduledRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DownloadQueueScheduled(Name alias, Table<DownloadQueueScheduledRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.download_queue_scheduled</code> table
     * reference
     */
    public DownloadQueueScheduled(String alias) {
        this(DSL.name(alias), DOWNLOAD_QUEUE_SCHEDULED);
    }

    /**
     * Create an aliased <code>public.download_queue_scheduled</code> table
     * reference
     */
    public DownloadQueueScheduled(Name alias) {
        this(alias, DOWNLOAD_QUEUE_SCHEDULED);
    }

    /**
     * Create a <code>public.download_queue_scheduled</code> table reference
     */
    public DownloadQueueScheduled() {
        this(DSL.name("download_queue_scheduled"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DownloadQueueScheduledRecord, Long> getIdentity() {
        return (Identity<DownloadQueueScheduledRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DownloadQueueScheduledRecord> getPrimaryKey() {
        return Keys.DOWNLOAD_QUEUE_SCHEDULED_PKEY;
    }

    @Override
    public List<Check<DownloadQueueScheduledRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("download_queue_scheduled_type_check"), "((type = ANY (ARRAY['ASSET'::text, 'BOARD'::text, 'TOPIC'::text])))", true)
        );
    }

    @Override
    public DownloadQueueScheduled as(String alias) {
        return new DownloadQueueScheduled(DSL.name(alias), this);
    }

    @Override
    public DownloadQueueScheduled as(Name alias) {
        return new DownloadQueueScheduled(alias, this);
    }

    @Override
    public DownloadQueueScheduled as(Table<?> alias) {
        return new DownloadQueueScheduled(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadQueueScheduled rename(String name) {
        return new DownloadQueueScheduled(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadQueueScheduled rename(Name name) {
        return new DownloadQueueScheduled(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadQueueScheduled rename(Table<?> name) {
        return new DownloadQueueScheduled(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueueScheduled where(Condition condition) {
        return new DownloadQueueScheduled(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueueScheduled where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueueScheduled where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueueScheduled where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadQueueScheduled where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadQueueScheduled where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadQueueScheduled where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadQueueScheduled where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueueScheduled whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadQueueScheduled whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
