/*
 * This file is generated by jOOQ.
 */
package pl.piotrmacha.lurker.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.piotrmacha.lurker.jooq.Indexes;
import pl.piotrmacha.lurker.jooq.Keys;
import pl.piotrmacha.lurker.jooq.Public;
import pl.piotrmacha.lurker.jooq.tables.Account.AccountPath;
import pl.piotrmacha.lurker.jooq.tables.Asset.AssetPath;
import pl.piotrmacha.lurker.jooq.tables.PostAttachment.PostAttachmentPath;
import pl.piotrmacha.lurker.jooq.tables.PostFulltext.PostFulltextPath;
import pl.piotrmacha.lurker.jooq.tables.Topic.TopicPath;
import pl.piotrmacha.lurker.jooq.tables.records.PostRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Post extends TableImpl<PostRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.post</code>
     */
    public static final Post POST = new Post();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostRecord> getRecordType() {
        return PostRecord.class;
    }

    /**
     * The column <code>public.post.id</code>.
     */
    public final TableField<PostRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.post.oid</code>.
     */
    public final TableField<PostRecord, String> OID = createField(DSL.name("oid"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.post.url</code>.
     */
    public final TableField<PostRecord, String> URL = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.post.author_id</code>.
     */
    public final TableField<PostRecord, Long> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.post.topic_id</code>.
     */
    public final TableField<PostRecord, Long> TOPIC_ID = createField(DSL.name("topic_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.post.content</code>.
     */
    public final TableField<PostRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.post.created_at</code>.
     */
    public final TableField<PostRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.post.last_update</code>.
     */
    public final TableField<PostRecord, OffsetDateTime> LAST_UPDATE = createField(DSL.name("last_update"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Post(Name alias, Table<PostRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Post(Name alias, Table<PostRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.post</code> table reference
     */
    public Post(String alias) {
        this(DSL.name(alias), POST);
    }

    /**
     * Create an aliased <code>public.post</code> table reference
     */
    public Post(Name alias) {
        this(alias, POST);
    }

    /**
     * Create a <code>public.post</code> table reference
     */
    public Post() {
        this(DSL.name("post"), null);
    }

    public <O extends Record> Post(Table<O> path, ForeignKey<O, PostRecord> childPath, InverseForeignKey<O, PostRecord> parentPath) {
        super(path, childPath, parentPath, POST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PostPath extends Post implements Path<PostRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PostPath(Table<O> path, ForeignKey<O, PostRecord> childPath, InverseForeignKey<O, PostRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PostPath(Name alias, Table<PostRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PostPath as(String alias) {
            return new PostPath(DSL.name(alias), this);
        }

        @Override
        public PostPath as(Name alias) {
            return new PostPath(alias, this);
        }

        @Override
        public PostPath as(Table<?> alias) {
            return new PostPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.POST_OID_IDX);
    }

    @Override
    public Identity<PostRecord, Long> getIdentity() {
        return (Identity<PostRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PostRecord> getPrimaryKey() {
        return Keys.POST_PKEY;
    }

    @Override
    public List<ForeignKey<PostRecord, ?>> getReferences() {
        return Arrays.asList(Keys.POST__POST_AUTHOR_ID_FKEY, Keys.POST__POST_TOPIC_ID_FKEY);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.POST__POST_AUTHOR_ID_FKEY, null);

        return _account;
    }

    private transient TopicPath _topic;

    /**
     * Get the implicit join path to the <code>public.topic</code> table.
     */
    public TopicPath topic() {
        if (_topic == null)
            _topic = new TopicPath(this, Keys.POST__POST_TOPIC_ID_FKEY, null);

        return _topic;
    }

    private transient PostAttachmentPath _postAttachment;

    /**
     * Get the implicit to-many join path to the
     * <code>public.post_attachment</code> table
     */
    public PostAttachmentPath postAttachment() {
        if (_postAttachment == null)
            _postAttachment = new PostAttachmentPath(this, null, Keys.POST_ATTACHMENT__POST_ATTACHMENT_POST_ID_FKEY.getInverseKey());

        return _postAttachment;
    }

    private transient PostFulltextPath _postFulltext;

    /**
     * Get the implicit to-many join path to the
     * <code>public.post_fulltext</code> table
     */
    public PostFulltextPath postFulltext() {
        if (_postFulltext == null)
            _postFulltext = new PostFulltextPath(this, null, Keys.POST_FULLTEXT__POST_FULLTEXT_POST_ID_FKEY.getInverseKey());

        return _postFulltext;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.asset</code>
     * table
     */
    public AssetPath asset() {
        return postAttachment().asset();
    }

    @Override
    public Post as(String alias) {
        return new Post(DSL.name(alias), this);
    }

    @Override
    public Post as(Name alias) {
        return new Post(alias, this);
    }

    @Override
    public Post as(Table<?> alias) {
        return new Post(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Post rename(String name) {
        return new Post(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Post rename(Name name) {
        return new Post(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Post rename(Table<?> name) {
        return new Post(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post where(Condition condition) {
        return new Post(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Post where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Post where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Post where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Post where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
