/*
 * This file is generated by jOOQ.
 */
package pl.piotrmacha.lurker.jooq.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import pl.piotrmacha.lurker.jooq.tables.Board;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BoardRecord extends UpdatableRecordImpl<BoardRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.board.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.board.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.board.oid</code>.
     */
    public void setOid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.board.oid</code>.
     */
    public String getOid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.board.url</code>.
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.board.url</code>.
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.board.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.board.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.board.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.board.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.board.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.board.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.board.last_update</code>.
     */
    public void setLastUpdate(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.board.last_update</code>.
     */
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BoardRecord
     */
    public BoardRecord() {
        super(Board.BOARD);
    }

    /**
     * Create a detached, initialised BoardRecord
     */
    public BoardRecord(Long id, String oid, String url, String name, String description, Long parentId, OffsetDateTime lastUpdate) {
        super(Board.BOARD);

        setId(id);
        setOid(oid);
        setUrl(url);
        setName(name);
        setDescription(description);
        setParentId(parentId);
        setLastUpdate(lastUpdate);
        resetChangedOnNotNull();
    }
}
