/*
 * This file is generated by jOOQ.
 */
package pl.piotrmacha.lurker.jooq.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import pl.piotrmacha.lurker.jooq.tables.Topic;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopicRecord extends UpdatableRecordImpl<TopicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.topic.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.topic.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.topic.oid</code>.
     */
    public void setOid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.topic.oid</code>.
     */
    public String getOid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.topic.url</code>.
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.topic.url</code>.
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.topic.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.topic.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.topic.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.topic.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.topic.board_id</code>.
     */
    public void setBoardId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.topic.board_id</code>.
     */
    public Long getBoardId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.topic.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.topic.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.topic.last_update</code>.
     */
    public void setLastUpdate(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.topic.last_update</code>.
     */
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopicRecord
     */
    public TopicRecord() {
        super(Topic.TOPIC);
    }

    /**
     * Create a detached, initialised TopicRecord
     */
    public TopicRecord(Long id, String oid, String url, String title, Long authorId, Long boardId, OffsetDateTime createdAt, OffsetDateTime lastUpdate) {
        super(Topic.TOPIC);

        setId(id);
        setOid(oid);
        setUrl(url);
        setTitle(title);
        setAuthorId(authorId);
        setBoardId(boardId);
        setCreatedAt(createdAt);
        setLastUpdate(lastUpdate);
        resetChangedOnNotNull();
    }
}
