/*
 * This file is generated by jOOQ.
 */
package pl.piotrmacha.lurker.jooq.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import pl.piotrmacha.lurker.jooq.tables.VisitedUrl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VisitedUrlRecord extends UpdatableRecordImpl<VisitedUrlRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.visited_url.url</code>.
     */
    public void setUrl(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.visited_url.url</code>.
     */
    public String getUrl() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.visited_url.visited_at</code>.
     */
    public void setVisitedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.visited_url.visited_at</code>.
     */
    public OffsetDateTime getVisitedAt() {
        return (OffsetDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VisitedUrlRecord
     */
    public VisitedUrlRecord() {
        super(VisitedUrl.VISITED_URL);
    }

    /**
     * Create a detached, initialised VisitedUrlRecord
     */
    public VisitedUrlRecord(String url, OffsetDateTime visitedAt) {
        super(VisitedUrl.VISITED_URL);

        setUrl(url);
        setVisitedAt(visitedAt);
        resetChangedOnNotNull();
    }
}
