/*
 * This file is generated by jOOQ.
 */
package pl.piotrmacha.lurker.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pl.piotrmacha.lurker.jooq.tables.Account;
import pl.piotrmacha.lurker.jooq.tables.Asset;
import pl.piotrmacha.lurker.jooq.tables.Board;
import pl.piotrmacha.lurker.jooq.tables.DownloadQueue;
import pl.piotrmacha.lurker.jooq.tables.DownloadQueueDone;
import pl.piotrmacha.lurker.jooq.tables.DownloadQueueFailure;
import pl.piotrmacha.lurker.jooq.tables.DownloadQueueScheduled;
import pl.piotrmacha.lurker.jooq.tables.FlywaySchemaHistory;
import pl.piotrmacha.lurker.jooq.tables.Post;
import pl.piotrmacha.lurker.jooq.tables.PostAttachment;
import pl.piotrmacha.lurker.jooq.tables.PostFulltext;
import pl.piotrmacha.lurker.jooq.tables.Topic;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.asset</code>.
     */
    public final Asset ASSET = Asset.ASSET;

    /**
     * The table <code>public.board</code>.
     */
    public final Board BOARD = Board.BOARD;

    /**
     * The table <code>public.download_queue</code>.
     */
    public final DownloadQueue DOWNLOAD_QUEUE = DownloadQueue.DOWNLOAD_QUEUE;

    /**
     * The table <code>public.download_queue_done</code>.
     */
    public final DownloadQueueDone DOWNLOAD_QUEUE_DONE = DownloadQueueDone.DOWNLOAD_QUEUE_DONE;

    /**
     * The table <code>public.download_queue_failure</code>.
     */
    public final DownloadQueueFailure DOWNLOAD_QUEUE_FAILURE = DownloadQueueFailure.DOWNLOAD_QUEUE_FAILURE;

    /**
     * The table <code>public.download_queue_scheduled</code>.
     */
    public final DownloadQueueScheduled DOWNLOAD_QUEUE_SCHEDULED = DownloadQueueScheduled.DOWNLOAD_QUEUE_SCHEDULED;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.post</code>.
     */
    public final Post POST = Post.POST;

    /**
     * The table <code>public.post_attachment</code>.
     */
    public final PostAttachment POST_ATTACHMENT = PostAttachment.POST_ATTACHMENT;

    /**
     * The table <code>public.post_fulltext</code>.
     */
    public final PostFulltext POST_FULLTEXT = PostFulltext.POST_FULLTEXT;

    /**
     * The table <code>public.topic</code>.
     */
    public final Topic TOPIC = Topic.TOPIC;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            Asset.ASSET,
            Board.BOARD,
            DownloadQueue.DOWNLOAD_QUEUE,
            DownloadQueueDone.DOWNLOAD_QUEUE_DONE,
            DownloadQueueFailure.DOWNLOAD_QUEUE_FAILURE,
            DownloadQueueScheduled.DOWNLOAD_QUEUE_SCHEDULED,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Post.POST,
            PostAttachment.POST_ATTACHMENT,
            PostFulltext.POST_FULLTEXT,
            Topic.TOPIC
        );
    }
}
