/*
 * This file is generated by jOOQ.
 */
package pl.piotrmacha.lurker.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>public.asset_id_seq</code>
     */
    public static final Sequence<Long> ASSET_ID_SEQ = Internal.createSequence("asset_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
