/*
 * This file is generated by jOOQ.
 */
package pl.piotrmacha.lurker.jooq;


import pl.piotrmacha.lurker.jooq.tables.Account;
import pl.piotrmacha.lurker.jooq.tables.Asset;
import pl.piotrmacha.lurker.jooq.tables.Category;
import pl.piotrmacha.lurker.jooq.tables.FlywaySchemaHistory;
import pl.piotrmacha.lurker.jooq.tables.Post;
import pl.piotrmacha.lurker.jooq.tables.Thread;
import pl.piotrmacha.lurker.jooq.tables.VisitedUrl;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.asset</code>.
     */
    public static final Asset ASSET = Asset.ASSET;

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.post</code>.
     */
    public static final Post POST = Post.POST;

    /**
     * The table <code>public.thread</code>.
     */
    public static final Thread THREAD = Thread.THREAD;

    /**
     * The table <code>public.visited_url</code>.
     */
    public static final VisitedUrl VISITED_URL = VisitedUrl.VISITED_URL;
}
