name: On Push
run-name: On Push ${{ github.ref_name }}
on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "main", "dev" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml