name: Release
run-name: Release ${{ github.ref_name }}
permissions: write-all

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ github.ref_name }}
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lurker-themodders
      - name: Prepare
        run: |
          zip -r lurker-themodders-java21.zip .env compose.yaml lurker-themodders.jar docker
          zip -r lurker-themodders-linux-amd64.zip .env compose.yaml lurker-themodders docker
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          release_notes: |
            ${{ github.event.release.body }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}